const names={all:"Tout",gants:"Gants",chaussures:"Chaussures",textile:"Textile",protections:"Protections"};
const grid=document.querySelector("#catalogue-grid"),count=document.querySelector("#catalogue-count"),search=document.querySelector("#catalogue-search"),filters=document.querySelector("#catalogue-filters");
document.head.insertAdjacentHTML("beforeend",'<link rel="stylesheet" href="finder.css">');
const catalogueNav=document.querySelector(".site-header nav");
if(catalogueNav&&!catalogueNav.querySelector('[href="trouve-ton-gant.html"]'))catalogueNav.querySelector('[href="catalogue.html"]').insertAdjacentHTML("afterend",'<a href="trouve-ton-gant.html">Trouve ton gant</a>');
let products=[],active=new URLSearchParams(location.search).get("category")||"all";
const textileFilters=document.querySelector('#catalogue-textile-filters'),club=document.querySelector('#catalogue-club'),tenue=document.querySelector('#catalogue-tenue');
const kitNames={domicile:'Domicile',exterieur:'Extérieur',third:'Third'};
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
if(!Object.hasOwn(names,active))active='all';
function jerseyCard(p){
 const url=escapeHtml(p.detailUrl||p.affiliateUrl);
 const external=p.detailUrl?'':' target="_blank" rel="sponsored noopener noreferrer"';
 return '<article class="catalog-product catalog-jersey"><a class="catalog-image" href="'+url+'"'+external+' aria-label="Voir '+escapeHtml(p.name)+'"><img src="'+escapeHtml(p.image)+'" alt="'+escapeHtml(p.name)+'" loading="lazy" width="600" height="600"><span>'+escapeHtml(kitNames[p.type]||p.type)+'</span></a><div class="catalog-info"><p>Textile · '+escapeHtml(p.club)+'</p><h2><a href="'+url+'"'+external+'>'+escapeHtml(p.name)+'</a></h2><small>'+escapeHtml(p.season)+' · Tailles : '+escapeHtml(p.sizes.join(' · '))+'<br>Boutique : '+escapeHtml(p.merchant)+'</small>'+(p.detailUrl?'<a href="'+escapeHtml(p.detailUrl)+'">Voir la fiche <i>→</i></a>':'')+'<a href="'+escapeHtml(p.affiliateUrl)+'" target="_blank" rel="sponsored noopener noreferrer">Voir chez le partenaire <i>↗</i></a></div></article>';
}
const price=value=>new Intl.NumberFormat("fr-CH",{style:"currency",currency:"CHF"}).format(value);
function card(p){if(p.club)return jerseyCard(p);const old=p.originalPrice?'<del>'+price(p.originalPrice)+'</del>':"";const url=p.productPage||"produit.html?id="+encodeURIComponent(p.id);return '<article class="catalog-product"><a class="catalog-image" href="'+url+'" style="background-image:url('+p.image+')" aria-label="Voir '+p.name+'"><span>'+p.badge+'</span><b>'+p.brand+'</b></a><div class="catalog-info"><p>'+names[p.category]+'</p><h2><a href="'+url+'">'+p.name+'</a></h2><small>'+p.description+'</small><div>'+(Number.isFinite(p.price)?'<strong>'+price(p.price)+'</strong>'+old:'')+'</div><a href="'+url+'">'+(p.productPage?'Voir la fiche':'Voir les détails')+' <i>→</i></a>'+(p.productPage?'<a href="comparateur.html?left='+encodeURIComponent(p.id)+'">Comparer <i>→</i></a>':'')+'</div></article>'}
function finderCard(){return '<article class="catalog-product finder-catalog-card"><a href="trouve-ton-gant.html" class="finder-card-inner"><span class="finder-card-kicker">OUTIL KEEPERLAB</span><strong>?</strong><h2>PAS SÛR DU<br>MODÈLE ?</h2><p>3 questions. Des recommandations expliquées.</p><b>Trouver mes gants <i>→</i></b></a></article>'}
function render(){textileFilters.hidden=active!=="all"&&active!=="textile";const term=search.value.trim().toLowerCase();const visible=products.filter(p=>(active==="all"||p.category===active)&&(!club.value||p.club===club.value)&&(!tenue.value||p.type===tenue.value)&&[p.name,p.brand,p.description,p.club,kitNames[p.type],p.season].filter(Boolean).join(" ").toLowerCase().includes(term));count.textContent=visible.length+" produit"+(visible.length!==1?"s":"");const cards=visible.map(card);if(!term&&!club.value&&!tenue.value&&(active==="all"||active==="gants"))cards.splice(Math.min(3,cards.length),0,finderCard());grid.innerHTML=cards.join("")||"<p class='catalog-empty'>Aucun produit ne correspond à votre recherche.</p>";filters.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.category===active))}
filters.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;active=b.dataset.category;if(active!=="all"&&active!=="textile"){club.value="";tenue.value="";}history.replaceState(null,"",active==="all"?"catalogue.html":"catalogue.html?category="+active);render()});
search.addEventListener("input",render);
club.addEventListener("change",render);
tenue.addEventListener("change",render);
Promise.all(['data/products.json','data/maillots.json'].map(async url=>{const response=await fetch(url);if(!response.ok)throw new Error('Catalogue indisponible');return response.json();})).then(([equipment,jerseys])=>{products=[...equipment,...jerseys.map(p=>({...p,category:'textile'}))];const clubs=[...new Set(jerseys.map(p=>p.club))].sort((a,b)=>a.localeCompare(b,'fr'));club.replaceChildren(new Option('Tous les clubs',''),...clubs.map(name=>new Option(name,name)));render()}).catch(()=>{count.textContent="Chargement impossible";grid.innerHTML="<p class='catalog-empty'>Le catalogue est momentanément indisponible.</p>"});
